### PR TITLE
Adjust to https://github.com/homalg-project/CAP_project/pull/1073

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
Unfortunately, the changes neither significantly improve the code nor the compilation time :( But at least there are not regressions :D

**Comment by zickgraf** [comment]
`Colimit` seems to be broken, I will investigate tomorrow.

**Comment by zickgraf** [comment]
This now also includes a logic template to adjust to https://github.com/homalg-project/FinSetsForCAP/pull/136.

**Comment by mohamed-barakat** [comment]
Why do so many commits appear above?

**Comment by zickgraf** [comment]
I messed up a rebase. But it should already be back to the three intended commits^^

**Review by mohamed-barakat — APPROVED** [review]
Very nice.

**Pull request merged**
