### PR TITLE
Adjust to https://github.com/homalg-project/CAP_project/pull/1215

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
Depends on https://github.com/homalg-project/Algebroids/pull/238 and https://github.com/homalg-project/CategoryConstructor/pull/87.

**Comment by mohamed-barakat** [comment]
> Depends on [homalg-project/Algebroids#238](https://github.com/homalg-project/Algebroids/pull/238) and [homalg-project/CategoryConstructor#87](https://github.com/homalg-project/CategoryConstructor/pull/87).

Does `ComplexesCategories` need to be updated as well?

**Comment by zickgraf** [comment]
> > Depends on [homalg-project/Algebroids#238](https://github.com/homalg-project/Algebroids/pull/238) and [homalg-project/CategoryConstructor#87](https://github.com/homalg-project/CategoryConstructor/pull/87).
> 
> Does `ComplexesCategories` need to be updated as well?

Ah, I missed that one, yes. But now there is a cyclic dependency :( I suggest merging this PR first (the tests pass locally on my PC).

**Comment by mohamed-barakat** [comment]
Done.

**Pull request merged**
