### PR TITLE
Saving the auxiliary map in the way is risky:

### PR DESCRIPTION
**Pull request by kamalsaleh**
(VectorSpaceObject(n,field) is a key dependent operation)

Sorry it was my mistake.

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Could you please bump the version?

**Comment by kamalsaleh** [comment]
Done!

**Comment by mohamed-barakat** [comment]
You need to bump it to 05 :)

**Comment by mohamed-barakat** [comment]
Many thanks.

**Pull request merged**
